### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by mrblog** [dwursteisen/image-api#1]
[ERROR] Failed to execute goal on project image-api: Could not resolve dependencies for project image-api:image-api:jar:1.0-SNAPSHOT: Could not find artifact org.scribe:scribe:jar:1.3.1-SNAPSHOT in google-code (http://google-gson.googlecode.com/svn/mavenrepo/) -> [Help 1]

**Comment by dwursteisen** [comment]
Image-api use a scribe version which us not yet release (see my scribe repository and set the version to 1.3.1-snapshot). I will try to upload this version into a repository for an easy build of this project.

**Comment by dwursteisen** [comment]
I just uploaded the missing jar and updated the pom.xml.

Just pull the repository and try again. 

Thanks for the issue.

**Comment by mrblog** [comment]
Sweet. Thanks!
